CREATE TABLE public.tmdb_movie_dataset_v11 (
    id INTEGER PRIMARY KEY,
	title varchar(5000) NULL,
	vote_average float8 NULL,
	vote_count int8 NULL,
	status varchar(5000) NULL,
	release_date varchar(5000) NULL,
	revenue int8 NULL,
	runtime int8 NULL,
	adult bool NULL,
	backdrop_path varchar(3000) NULL,
	budget int8 NULL,
	homepage varchar(3000) NULL,
	imdb_id varchar(500) NULL,
	original_language varchar(5000) NULL,
	original_title varchar(640) NULL,
	overview varchar(20000) NULL,
	popularity float8 NULL,
	poster_path varchar(3000) NULL,
	tagline text NULL,
	genres varchar(30000) NULL,
	production_companies varchar(4000) NULL,
	production_countries varchar(5000) NULL,
	spoken_languages varchar(4000) NULL,
	keywords varchar(40000) NULL
);

CREATE TEMP TABLE temp_tmdb_movie_dataset_v11 AS
SELECT * FROM tmdb_movie_dataset_v11 LIMIT 0;

COPY temp_tmdb_movie_dataset_v11
FROM '/TMDB_movie_dataset_v11/TMDB_movie_dataset_v11.csv'
DELIMITER ','
CSV HEADER;

INSERT INTO tmdb_movie_dataset_v11
SELECT * FROM temp_tmdb_movie_dataset_v11
ON CONFLICT (id) DO NOTHING;

ALTER TABLE tmdb_movie_dataset_v11
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;