version: '3.8'
services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: Postgre2022!
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/